spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/q199571/microconfig
          username: q199571
          password: 199571
          basedir: E:\microcloud\product-master\bserver-config\basedir
eureka:
  client:
    service-url:
      defaultZone: http://hxh:hxh@localhost:8761/eureka/
management:
  endpoints:
    web:
      expose: "*"
server:
  port: 7001